### PR TITLE
Windows Agent bootstrapping leveraging Powershell

### PR DESCRIPTION
**Pull request by jshcodes**
Falcon Sensor installation leveraging Powershell and SSM.

### CODE REVIEW

**Comment by redhatrises** [comment]
QQ, is the Powershell utilizing psFalcon?

**Comment by jshcodes** [comment]
> QQ, is the Powershell utilizing psFalcon?

This iteration doesn't.  We are going to be working on an example that does to add to this repo as well.

**Review by jhseceng — APPROVED** [review]
We will add these to a technote describing usage

**Review by shawndwells — COMMENTED** [review]
There are /many/ PowerShell script examples on installing a sensor. Do we really want to maintain another one?

**Pull request merged**
