### PR TITLE
Fix spell checking CI

### PR DESCRIPTION
**Pull request by isimluk**
It seems that spellchecking CI has been failing for a while (see [history](https://github.com/CrowdStrike/Cloud-AWS/actions?query=workflow%3A%22Check+Spelling%22)), let's fix it.

Wip until it passes.

### CODE REVIEW

**Comment by shawndwells** [comment]
@jhseceng @isimluk should we just turn off spell check? Seems more annoying than useful.

p.s. realize I'm the one who enabled it =/ Intent was to check our markdown files but it is just getting in the way.

**Comment by isimluk** [comment]
No worries, we can disable it, I just want to spend few more moments on it before I thrown in the towel.

**Comment by isimluk** [comment]
It is all 💚

**Review by shawndwells — APPROVED** [review]
Of course you fixed this. Nice job!

**Pull request merged**
