### PR TITLE
Discover script

### PR DESCRIPTION
**Pull request by jhseceng**
Added lambda files for Privatelink demo

### CODE REVIEW

**Review by jshcodes — APPROVED** [review]
LGTM

**Comment by redhatrises** [comment]
Just an FYI... The 2 merge commits of master ultimately make it hard to review history and makes it harder to understand changes and muddies up the commit tree. For future, would recommend `git rebase -i` on your branch or making sure to pull changes before creating a new branch.

**Review by isimluk — APPROVED** [review]
👍

**Comment by shawndwells** [comment]
> Just an FYI... The 2 merge commits of master ultimately make it hard to review history and makes it harder to understand changes and muddies up the commit tree. For future, would recommend `git rebase -i` on your branch or making sure to pull changes before creating a new branch.

+1

Is there a way to systematically enforce that? Many projects have 'prevent merge commits' (or whatever it's called) enabled. Is there a better way that we should consider?

**Pull request merged**
